### ISSUE TITLE
windows DNS resolution + zeronsd 

### ISSUE THREAD

**Issue by Kegelcizer** [zerotier/zeronsd#88] opened 2021-06-25 21:01 UTC
- zerotier container running and connected to the network
- zeronsd container running
- ~~2nd client windows with allow dns checked, but the interface does not have the dns server on it~~ NRPT works
- ping works from both clients
- resolving from both clients does not work

If anything else is needed, please ask and I will add it here and on the gist.

Output of dig, nslookup, container, etc
https://gist.github.com/Kegelcizer/0bbba2ab8e95c5a965337edf69e064dd

**Comment by glimberg** [comment] 2021-06-25 21:08
ZeroTier does not put the dns server on the adapter.  It uses Windows' NRPT system.  You can view the configuration in a PowerShell prompt via [Get-DnsClientNrptRule](https://docs.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientnrptrule?view=windowsserver2019-ps)

**Comment by glimberg** [comment] 2021-06-25 21:19
Example output from Windows:

```
PS C:\WINDOWS\system32> Get-DnsClientNrptRule


Name                             : {565B7393-CAD2-4391-BDEE-5141E545186C}
Version                          : 2
Namespace                        : {.dnstest.zt}
IPsecCARestriction               :
DirectAccessDnsServers           :
DirectAccessEnabled              : False
DirectAccessProxyType            :
DirectAccessProxyName            :
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   :
NameServers                      : 192.168.192.73
DnsSecEnabled                    : False
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         :
DnsSecValidationRequired         :
NameEncoding                     : Disable
DisplayName                      :
Comment                          : d5e04297a1dd5aea
```

**Comment by Kegelcizer** [comment] 2021-06-25 21:53
Ok so NRPT works, crossed out one issue.
Edited post and gist.
Thank you,

**Comment by erikh** [comment] 2021-06-25 21:54
Thanks @glimberg. The problem is partially that DNS is not resolving for @Kegelcizer, which we have diagnosed over discord. This is only tangentially related to windows.

**Comment by erikh** [comment] 2021-06-25 23:05
so Grant did some sleuthing and discovered a bug in zeronsd where it misreports the nameservers to central in a few situations that you may be seeing. I'm going to kick out a patch RSN but likely this won't be fixed until 0.2.2 is released.

**Comment by erikh** [comment] 2021-06-25 23:06
for now, if you want to try editing your nameserver to remove the /xxx portion at the end of it, and try resolution after 30-60 seconds after the change is made -- without restarting zeronsd, which will re-set that value -- that would be useful info if you have the time.

**Comment by erikh** [comment] 2021-06-26 00:39
0.2.2 was released, which might help with this. Please try it if you get time and lmk!

**Comment by Kegelcizer** [comment] 2021-06-26 07:08
Pulled the latest zeronsd image and recreated the container.
No changes to dig and nslookup

dig +short @10.0.1.2 hz.lan.lo

nslookup hz.lan.ro 10.0.1.2
Server:  UnKnown
Address:  10.0.1.2

*** UnKnown can't find hz.lan.ro: Non-existent domain

**Comment by erikh** [comment] 2021-07-17 06:38
ok, I have reproduced this on windows only. Windows resolving using a linux zeronsd works fine.

**Comment by erikh** [comment] 2021-07-17 06:51
I'll need to look at this tomorrow, but I strongly suspect it's firewall related. Will continue to chase this down.

**Comment by erikh** [comment] 2022-02-22 03:27
@Kegelcizer finally got around to fixing this. sorry it took so damn long! :)

**Closed** 2022-02-22 03:27 UTC
