### ISSUE TITLE
Some way to list all the host names on a zerotier network without being a network administrator

### ISSUE THREAD

**Issue by laduke** [zerotier/zeronsd#1] opened 2021-05-04 19:29 UTC
Hi!

It'd be cool to be able to see the names of everything on the network without having to go to Central. 
We talked about allowing AXFR from localhost and that makes sense. 
But I also think allowing it for the whole zerotier subnet makes sense too for some uses at least, like the home lab type network. So behind a flag? 

For example, I'm going to be running zeronsd on some server, but spending most of my time working and administrating stuff from a laptop, and I can never remember the names of things. 

I just saw on the trust-dns readme AXFR is an on/off thing at the moment. No limiting by address.

Other options would be.. Host as hostsfile or something on some http endpoint in zeronsd, which seems less good.

**Comment by erikh** [comment] 2021-05-04 19:32
I had `dump` command in here early on that I could re-add that might help a bit. Let me explore this over the next week.

**Comment by laduke** [comment] 2021-05-04 19:37
Hopefully not repeating myself too badly, but I want to get a list of the hosts on a network from a client computer that isn't the zeronsd server.

**Comment by erikh** [comment] 2021-05-04 19:40
Sorry. Misunderstood. I think axfr isn’t going to be very safe for that but
I’ll have to look again. What if I just kept a TXT record up to date?

**Comment by laduke** [comment] 2021-05-04 20:40
You know better than I do! I'm not sure how big a TXT record can be. 

I was thinking in many cases you trust everything/everybody on a zerotier network, so AXFR would be fine?

**Comment by erikh** [comment] 2021-05-04 20:47
ah. I guess I missed the memo there, only 255 chars unless you get into hax that we'd almost certainly need a custom client for (defeating the purpose).

I'll look into scoped/general AXFR soon.

**Comment by erikh** [comment] 2021-05-05 10:11
So I played, and the only way to do AXFR without modifying trust-dns itself is to allow updates to the zone, which seems like a very terrible idea. :)

I think it might be better to add a small API to this thing for this purpose, or provide a second client to central which just generates hosts files from central records. WDYT?

**Comment by erikh** [comment] 2021-05-05 10:13
Just ignore that second suggestion because I think it's like the third time I've suggested that in this thread. I've updated the topic to more appropriately remind me that the unprivileged bit is important. :D

**Comment by laduke** [comment] 2021-05-05 14:40
> only way to do AXFR without modifying trust-dns itself is to allow updates to the zone

that doesn't sound good!

I don't want to pressure some weird, out of scope feature. Should we close? Or let it sit for a while? 

I think having the pointer records now will help a bunch too.

**Comment by erikh** [comment] 2021-05-05 19:04
Let's leave it open... Maybe some other method will become obvious or
someone can come in and correct me
heh

**Comment by erikh** [comment] 2021-05-13 21:15
I think I will solve this with a http service that returns plain json and uses an allow list of hosts. Work for you?

**Comment by laduke** [comment] 2021-05-13 22:53
Sure!

**Comment by erikh** [comment] 2021-05-13 22:54
ok. I'm going to do a ticket on configuration files, I'll tag you in it so we can discuss it more there.

**Comment by erikh** [comment] 2021-06-11 03:16
Confirmed you can do this with `nmap -sP <subnet>`. I'm going to close this until we have more needs here.

**Closed by erikh** 2021-06-11 03:16 UTC
Labels: enhancement

**Comment by laduke** [comment] 2021-06-11 04:03
`nmap -sL --dns-server=100.64.64.9 100.64.64.0/24` goes fast
