### ISSUE TITLE
Error during installation of zeronsd_0.2.2_amd64.deb on ubuntu 18.04

### ISSUE THREAD

**Issue by cyberchucktx** [zerotier/zeronsd#90] opened 2021-06-26 22:29 UTC
Error during installation of zeronsd_0.2.2_amd64.deb on ubuntu 18.04

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

Got the following when attempting install under Ubuntu. 

Suggestions? 

Charlie

=====

% dpkg -i zeronsd_0.2.2_amd64.deb
(Reading database ... 397800 files and directories currently installed.)
Preparing to unpack zeronsd_0.2.2_amd64.deb ...
Unpacking zeronsd (0.2.2) over (0.2.2) ...
dpkg: dependency problems prevent configuration of zeronsd:
 zeronsd depends on libssl1.1 (>= 1.1.1d); however:
  Version of libssl1.1:amd64 on system is 1.1.1-1ubuntu2.1~18.04.9.
 zeronsd depends on libc6 (>= 2.28); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.4.

dpkg: error processing package zeronsd (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 zeronsd

**Comment by erikh** [comment] 2021-06-26 23:12
Ok that's a standard error when libc is out of date, likely caused by the age of your distro. I think 18.04 is EOL now? I can't recall. I will look into this, but probably not for a few weeks most likely. Sorry.

For now, you can always build a binary on your target architecture with [rustup](https://rustup.rs) and [cargo](https://crates.io). Just type:

```
cargo install zeronsd
```

To install it to an appropriate place in your homedir. More detailed instructions are in the README for this method. 

Assuming there's no inherent conflict in the libc API (extremely unlikely) you should be on your way with the versions you need.

**Comment by cyberchucktx** [comment] 2021-06-27 01:21
Erik: 
18.04 EOL is April 2023. https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes
I'll try RUSTUP or CARGO. 
FYI,Charlie
 

    On Saturday, June 26, 2021, 06:13:02 PM CDT, Erik Hollensbe ***@***.***> wrote:  
 
 


Ok that's a standard error when libc is out of date, likely caused by the age of your distro. I think 18.04 is EOL now? I can't recall. I will look into this, but probably not for a few weeks most likely. Sorry.

For now, you can always build a binary on your target architecture with rustup and cargo. Just type:
cargo install zeronsd

To install it to an appropriate place in your homedir. More detailed instructions are in the README for this method.

Assuming there's no inherent conflict in the libc API (extremely unlikely) you should be on your way with the versions you need.

**Comment by erikh** [comment] 2021-07-28 05:25
Seeing as the release instructions are already [pretty involved for a single person](https://github.com/zerotier/zeronsd/blob/main/docs/release.md) I'm sorry, I'm going to punt on this for now. Until there's significant interest, for now you can do this on a ubuntu 18.04 host to generate a package from source:

`cargo deb`

This requires you have a rust host on at least one build-ready box.

Let's leave this open though; if we can get a few likes/comments in here saying this is what people want, I'll add it to the release. Just want to be sure I'm spending my time in the right places; I hope that's an ok thing to request.

HTH!

**Comment by cyberchucktx** [comment] 2021-07-28 14:48
Erik et al: 

I, for one, appreciate the time and effort you've put into this project; I appreciate 
anyone who's devoted significant time to Open Source Projects. 

For me I can figure out ways around the DNS situation; I would urge you (the author) to concentrateon other projects or other parts of the ZeroTier ecosystem. 

Thanks again, 
Charlie in Houston, TX 
 

    On Wednesday, July 28, 2021, 12:26:11 AM CDT, Erik Hollensbe ***@***.***> wrote:  
 
 


Seeing as the release instructions are already pretty involved for a single person I'm sorry, I'm going to punt on this for now. Until there's significant interest, for now you can do this on a ubuntu 18.04 host to generate a package from source:

cargo deb

This requires you have a rust host on at least one build-ready box.

Let's leave this open though; if we can get a few likes/comments in here saying this is what people want, I'll add it to the release. Just want to be sure I'm spending my time in the right places; I hope that's an ok thing to request.

HTH!

**Comment by erikh** [comment] 2022-02-01 00:52
closing this as I've seen no other complaints on this front; while 18i.04 and earlier would be nice to support, it's a bear to deal with all the platforms we support as it is :) I hope you're ok with that.

**Closed by erikh** 2022-02-01 00:52 UTC
